name: closed
version: 0.0.0.0 # maintained by semantic-release
synopsis: Integers bounded by a closed interval
description: Integers bounded by a closed interval checked at compile time
category: Data
author: Chris Parks <chris@freckle.com>
maintainer: Freckle Education <engineering@freckle.com>
github: frontrowed/closed
license: MIT

dependencies:
  - aeson
  - base >= 4.9 && < 5
  - cassava
  - persistent
  - text

library:
  source-dirs:
    - library
  dependencies:
    - deepseq
    - hashable
    - random
    - QuickCheck

tests:
  readme:
    main: README.lhs
    ghc-options: -Wall -pgmL markdown-unlit
    dependencies:
      - closed
      - hspec
      - markdown-unlit
      - vector

extra-source-files:
  - README.lhs
