name: closed
version: "0.1.0"
synopsis: Integers bounded by a closed interval
description: Integers bounded by a closed interval
category: Data
author: Chris Parks <chris@frontrowed.com>
maintainer: Front Row Education <engineering@frontrowed.com>
github: frontrowed/closed
license: MIT

dependencies:
  - base >= 4.9 && < 5
  - deepseq
  - aeson
  - cassava
  - hashable
  - QuickCheck

library:
  source-dirs:
    - library

tests:
  readme:
    main: README.lhs
    ghc-options: -Wall -pgmL markdown-unlit
    dependencies:
      - base
      - closed
      - hspec
      - markdown-unlit
      - vector

extra-source-files:
  - README.lhs
